import { useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Language = 'en' | 'sq'

const content = {
  en: { nav: ['Services', 'Solutions', 'About', 'Contact'], eyebrow: 'Business operations, without the overhead', title: 'The office behind your next chapter.', intro: 'Remote Office helps businesses, NGOs and individuals operate with clarity, compliance and momentum, even without a traditional office and team.', explore: 'Explore services', talk: 'Talk to our team', proof: 'A professional partner for everyday progress', servicesLabel: 'What we do', servicesTitle: 'Everything your operation needs to move forward.', servicesIntro: 'From financial control to systems that work together, we bring structure and reliable support to the work that matters.', services: [['01', 'Financial services', 'Accounting, reporting, payroll and practical financial guidance that keeps your business informed and compliant.'], ['02', 'Legal & administration', 'Administrative and legal support designed around the real needs of companies, NGOs and individuals in Albania.'], ['03', 'Application development', 'Useful digital products and custom workflows that simplify work, decisions and service delivery.'], ['04', 'Operational structuring', 'We design the processes, tools and documentation that help a lean team perform like a strong one.']], solutionsLabel: 'Digital solutions', solutionsTitle: 'Your essential tools, gathered in one place.', solutionsIntro: 'Access the applications and support services that keep remote operations connected.', apps: [['Konsulence', 'Financial and business support platform', 'https://konsulence.al'], ['Remote Office Portal', 'Your digital operations workspace', 'https://portal.remoteoffice.al'], ['Business Workspace', 'A space reserved for your next solution', '#']], trustLabel: 'Built on trust', trustTitle: 'Professional work. Christian integrity. Practical impact.', trustBody: 'As Christian business people in mission and in the professional world, integrity is our core value. We help clients increase efficiency and remain compliant through transparent, responsible guidance, never through hiding taxes.', certBody: 'Certified support for modern bookkeeping and financial workflows.', teamLabel: 'The people behind the work', teamTitle: 'A capable team, ready to join yours.', team: [['Arben K.', 'Managing Partner'], ['Elira M.', 'Accounting & Compliance'], ['Jonida P.', 'Operations & Systems']], contactLabel: 'Start a conversation', contactTitle: 'Make your operation lighter.', contactBody: 'Tell us what is slowing your work down. We will help you find a clearer way forward.', name: 'Your name', email: 'Email address', message: 'How can we help?', send: 'Send enquiry', sent: 'Thank you. We will be in touch shortly.', footer: 'A service provider of PGROUP INC', address: 'Rruga e Barrikadave, Nr. 125, Tirane 1016, Albania', hours: 'Monday - Friday, 9:00 - 15:30' },
  sq: { nav: ['Shërbimet', 'Zgjidhjet', 'Rreth nesh', 'Kontakt'], eyebrow: 'Operacione biznesi, pa kostot e një zyre', title: 'Zyra pas kapitullit tuaj të ardhshëm.', intro: 'Remote Office ndihmon bizneset, OJQ-të dhe individët të operojnë me qartësi, përputhshmëri dhe ritëm, edhe pa një zyrë dhe ekip tradicional.', explore: 'Shiko shërbimet', talk: 'Flisni me ekipin', proof: 'Partner profesional për progresin e përditshëm', servicesLabel: 'Çfarë bëjmë', servicesTitle: 'Gjithçka që i duhet operacionit tuaj për të ecur përpara.', servicesIntro: 'Nga kontrolli financiar te sistemet që punojnë së bashku, sjellim strukturë dhe mbështetje të besueshme në punën që ka rëndësi.', services: [['01', 'Shërbime financiare', 'Kontabilitet, raporte, paga dhe këshillim financiar praktik që e mban biznesin tuaj të informuar dhe në përputhje me ligjin.'], ['02', 'Ligjore dhe administrim', 'Mbështetje administrative dhe ligjore sipas nevojave reale të kompanive, OJQ-ve dhe individëve në Shqipëri.'], ['03', 'Zhvillim aplikacionesh', 'Produkte digjitale dhe procese të personalizuara që thjeshtojnë punën, vendimet dhe ofrimin e shërbimeve.'], ['04', 'Strukturim operacional', 'Projektojmë proceset, mjetet dhe dokumentacionin që ndihmojnë një ekip të vogël të funksionojë si një ekip i fortë.']], solutionsLabel: 'Zgjidhje digjitale', solutionsTitle: 'Mjetet tuaja thelbësore, në një vend.', solutionsIntro: 'Aksesoni aplikacionet dhe shërbimet që mbajnë operacionet në distancë të lidhura.', apps: [['Konsulence', 'Platformë për mbështetje financiare dhe biznesi', 'https://konsulence.al'], ['Remote Office Portal', 'Hapësira juaj digjitale e punës', 'https://portal.remoteoffice.al'], ['Business Workspace', 'Një hapësirë për zgjidhjen tuaj të ardhshme', '#']], trustLabel: 'Ndërtuar mbi besim', trustTitle: 'Punë profesionale. Integritet i krishterë. Ndikim praktik.', trustBody: 'Si biznesmenë të krishterë në mision dhe në botën profesionale, integriteti është vlera jonë themelore. Ndihmojmë klientët të rrisin efikasitetin dhe të jenë në përputhje me ligjin përmes udhëzimit transparent e të përgjegjshëm, jo duke fshehur taksat.', certBody: 'Mbështetje e certifikuar për kontabilitetin modern dhe proceset financiare.', teamLabel: 'Njerëzit pas punës', teamTitle: 'Një ekip i aftë, gati t’i bashkohet ekipit tuaj.', team: [['Arben K.', 'Partner Menaxhues'], ['Elira M.', 'Kontabilitet dhe Përputhshmëri'], ['Jonida P.', 'Operacione dhe Sisteme']], contactLabel: 'Nisni një bisedë', contactTitle: 'Bëjeni operacionin tuaj më të lehtë.', contactBody: 'Na tregoni çfarë po ngadalëson punën tuaj. Do t’ju ndihmojmë të gjeni një mënyrë më të qartë përpara.', name: 'Emri juaj', email: 'Adresa e emailit', message: 'Si mund t’ju ndihmojmë?', send: 'Dërgo kërkesën', sent: 'Faleminderit. Do t’ju kontaktojmë së shpejti.', footer: 'Ofrues shërbimesh i PGROUP INC', address: 'Rruga e Barrikadave, Nr. 125, Tiranë 1016, Shqipëri', hours: 'E hënë - E premte, 09:00 - 15:30' },
} as const

function App() {
  const [language, setLanguage] = useState<Language>('en')
  const [sent, setSent] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const text = content[language]
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true) }
  const closeMenu = () => setMenuOpen(false)

  return (
    <div className="site-shell">
      <header className="nav"><a className="brand" href="#top" onClick={closeMenu}><span className="brand-mark">R</span><span>REMOTE<br /><b>OFFICE</b></span></a><nav className={menuOpen ? 'menu-open' : ''}>{text.nav.map((item, index) => <a key={item} href={['#services', '#solutions', '#about', '#contact'][index]} onClick={closeMenu}>{item}</a>)}</nav><div className="nav-actions"><a className="whatsapp" href="https://wa.me/355692064518" target="_blank" rel="noreferrer">WhatsApp</a><button className="language" onClick={() => setLanguage(language === 'en' ? 'sq' : 'en')} aria-label="Change language">{language === 'en' ? 'SQ' : 'EN'}</button><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label={menuOpen ? 'Close menu' : 'Open menu'}><span></span><span></span></button></div></header>
      <main id="top"><section className="hero-section"><div className="hero-copy"><p className="eyebrow">{text.eyebrow}</p><h1>{text.title}</h1><p className="hero-intro">{text.intro}</p><div className="hero-actions"><a className="button button-primary" href="#services">{text.explore}<span>↗</span></a><a className="button button-quiet" href="#contact">{text.talk}<span>↗</span></a></div></div><div className="hero-visual"><div className="image-placeholder"><span>IMAGE SPACE</span><small>Replace with company or team image</small></div><div className="hero-stamp">EST.<br /><strong>2024</strong><br />ALBANIA</div></div></section>
      <div className="trust-line"><span>{text.proof}</span><span>PGROUP INC · M01419018I</span><span>ALBANIA · EUROPE</span></div>
      <section className="content-section" id="services"><div className="section-heading"><p className="eyebrow">{text.servicesLabel}</p><h2>{text.servicesTitle}</h2><p>{text.servicesIntro}</p></div><div className="service-grid">{text.services.map(([number, title, body]) => <article className="service-card" key={number}><span className="service-number">{number}</span><h3>{title}</h3><p>{body}</p><a href="#contact">Learn more <span>↗</span></a></article>)}</div></section>
      <section className="solutions-section" id="solutions"><div className="section-heading"><p className="eyebrow">{text.solutionsLabel}</p><h2>{text.solutionsTitle}</h2><p>{text.solutionsIntro}</p></div><div className="app-grid">{text.apps.map(([name, body, link], index) => <a className="app-card" href={link} target={link !== '#' ? '_blank' : undefined} rel="noreferrer" key={name}><span className={`app-logo logo-${index}`}>{index === 0 ? 'K' : index === 1 ? 'RO' : '+'}</span><span><strong>{name}</strong><small>{body}</small></span><span className="arrow">↗</span></a>)}</div></section>
      <section className="about-section" id="about"><div className="about-image image-placeholder"><span>LOGO / CERTIFICATION SPACE</span><small>Add brand assets here</small></div><div className="about-copy"><p className="eyebrow">{text.trustLabel}</p><h2>{text.trustTitle}</h2><p>{text.trustBody}</p><div className="certification"><span className="cert-badge">Q</span><span><strong>QuickBooks Online ProAdvisor</strong><small>{text.certBody}</small></span><span className="verified">Verified</span></div></div></section>
      <section className="team-section"><div className="section-heading"><p className="eyebrow">{text.teamLabel}</p><h2>{text.teamTitle}</h2></div><div className="team-grid">{text.team.map(([name, role]) => <div className="team-card" key={name}><div className="avatar image-placeholder"><span>PHOTO</span></div><strong>{name}</strong><small>{role}</small></div>)}</div></section>
      <section className="contact-section" id="contact"><div className="contact-copy"><p className="eyebrow">{text.contactLabel}</p><h2>{text.contactTitle}</h2><p>{text.contactBody}</p><div className="contact-links"><a href="tel:+355692064518">+355 69 206 4518</a><a href="mailto:info@remoteoffice.al">info@remoteoffice.al</a><a href="https://wa.me/355692064518" target="_blank" rel="noreferrer">WhatsApp support ↗</a></div></div><form className="contact-form" onSubmit={handleSubmit}><label>{text.name}<input required name="name" placeholder={text.name} /></label><label>{text.email}<input required type="email" name="email" placeholder={text.email} /></label><label>{text.message}<textarea required name="message" placeholder={text.message} rows={4} /></label><button className="button button-primary" type="submit">{text.send}<span>↗</span></button>{sent && <p className="form-success">{text.sent}</p>}</form></section></main>
      <footer><div className="brand"><span className="brand-mark">R</span><span>REMOTE<br /><b>OFFICE</b></span></div><p>{text.footer}<br />{text.address}<br />{text.hours}</p><div className="socials"><a href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://www.instagram.com" target="_blank" rel="noreferrer">Instagram</a><a href="https://www.facebook.com" target="_blank" rel="noreferrer">Facebook</a></div></footer>
    </div>
  )
}

export default App
